
package com.elle.elle_gui.presentation;

import com.elle.elle_gui.logic.Tab;
import com.elle.elle_gui.old.CreateDocumentFilter;
import java.sql.Statement;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.text.AbstractDocument;

/**
 * ELLE_GUI_Frame
 * @author Carlos Igreja
 * @since 8-14-2015
 * @version ELLE_GUI-0.6.9
 */
public class ELLE_GUI_Frame extends JFrame {
    
    // Edit the version and date it was created for new archives and jars
    private final String CREATION_DATE = "2015-08-13";  
    private final String VERSION = "0.8.3c";   
    
    // attributes
    private Map<String,Tab> tabs; // stores individual tabName information
    private static Statement statement;
    private String database;
    
    // components
    private static ELLE_GUI_Frame instance;
    private LoginWindow loginWindow;

    /**
     * ELLE_GUI_Frame
     * Creates the ELLE_GUI_Frame 
     * which is the main window of the application
     */
    public ELLE_GUI_Frame() {
        initComponents();
        setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        setTitle("Elle GUI");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCTRLPanel = new javax.swing.JPanel();
        btnPositions = new javax.swing.JButton();
        btnTrades = new javax.swing.JButton();
        btnAllocations = new javax.swing.JButton();
        btnSymbol = new javax.swing.JButton();
        btnDateRange = new javax.swing.JButton();
        labelNumOfRecords = new javax.swing.JLabel();
        checkBoxSymbol = new javax.swing.JCheckBox();
        checkBoxDateRange = new javax.swing.JCheckBox();
        labelHyphen = new javax.swing.JLabel();
        textFieldSymbol = new javax.swing.JTextField();
        textFieldStartDate = new javax.swing.JTextField();
        textFieldEndDate = new javax.swing.JTextField();
        btnClearAllFilters = new java.awt.Button();
        panelSQL = new javax.swing.JPanel();
        scrollPaneSQL = new javax.swing.JScrollPane();
        textAreaSQL = new javax.swing.JTextArea();
        btnEnterSQL = new javax.swing.JButton();
        btnClearSQL = new javax.swing.JButton();
        panelShowTables = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuConnections = new javax.swing.JMenu();
        menuItemLocal = new javax.swing.JMenuItem();
        menuItemAWS = new javax.swing.JMenuItem();
        menuItemDummy = new javax.swing.JMenuItem();
        menuItemRead = new javax.swing.JMenuItem();
        menuPrint = new javax.swing.JMenu();
        menuItemPrintGUI = new javax.swing.JMenuItem();
        menuItemPrintDisplayWindow = new javax.swing.JMenuItem();
        menuItemSave = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuItemConnection = new javax.swing.JMenuItem();
        menuFind = new javax.swing.JMenu();
        menuReports = new javax.swing.JMenu();
        menuTools = new javax.swing.JMenu();
        menuItemReconcile = new javax.swing.JMenuItem();
        menuItemShowMatches = new javax.swing.JMenuItem();
        menuItemIB8949 = new javax.swing.JMenuItem();
        menuItemTL8949 = new javax.swing.JMenuItem();
        menuLoad = new javax.swing.JMenu();
        menuItemLoadFile = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();
        menuItemLog = new javax.swing.JMenuItem();
        menuItemSqlCommand = new javax.swing.JMenuItem();
        menuItemTrades = new javax.swing.JMenuItem();
        menuItemPositions = new javax.swing.JMenuItem();
        menuItemIB = new javax.swing.JMenuItem();
        menuItemTL = new javax.swing.JMenuItem();
        menuItemLoadsTable = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuOther = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPositions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elle/elle_gui/images/button1.png"))); // NOI18N
        btnPositions.setText("Positions");
        btnPositions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPositions.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPositions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPositionsActionPerformed(evt);
            }
        });

        btnTrades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elle/elle_gui/images/button1.png"))); // NOI18N
        btnTrades.setText("Trades");
        btnTrades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTrades.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTradesActionPerformed(evt);
            }
        });

        btnAllocations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elle/elle_gui/images/button3.png"))); // NOI18N
        btnAllocations.setText("Allocations");
        btnAllocations.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAllocations.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAllocations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllocationsActionPerformed(evt);
            }
        });

        btnSymbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elle/elle_gui/images/filter.png"))); // NOI18N
        btnSymbol.setText(" ");
        btnSymbol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSymbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSymbolActionPerformed(evt);
            }
        });

        btnDateRange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elle/elle_gui/images/filter.png"))); // NOI18N
        btnDateRange.setText(" ");
        btnDateRange.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDateRange.setIconTextGap(0);
        btnDateRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateRangeActionPerformed(evt);
            }
        });

        labelNumOfRecords.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelNumOfRecords.setText("Number of Records: 0");

        checkBoxSymbol.setText("Symbol");
        checkBoxSymbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSymbolActionPerformed(evt);
            }
        });

        checkBoxDateRange.setText("Date Range");
        checkBoxDateRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxDateRangeActionPerformed(evt);
            }
        });

        labelHyphen.setText("-");

        btnClearAllFilters.setActionCommand("Clear All Filters");
        btnClearAllFilters.setLabel("Clear All Filters");
        btnClearAllFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAllFiltersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCTRLPanelLayout = new javax.swing.GroupLayout(panelCTRLPanel);
        panelCTRLPanel.setLayout(panelCTRLPanelLayout);
        panelCTRLPanelLayout.setHorizontalGroup(
            panelCTRLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCTRLPanelLayout.createSequentialGroup()
                .addGroup(panelCTRLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCTRLPanelLayout.createSequentialGroup()
                        .addComponent(btnPositions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTrades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCTRLPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelNumOfRecords)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAllocations)
                .addGap(334, 334, 334)
                .addGroup(panelCTRLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCTRLPanelLayout.createSequentialGroup()
                        .addComponent(textFieldSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkBoxSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelCTRLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxDateRange)
                    .addGroup(panelCTRLPanelLayout.createSequentialGroup()
                        .addComponent(textFieldStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelHyphen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelCTRLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelCTRLPanelLayout.createSequentialGroup()
                                .addComponent(textFieldEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDateRange, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnClearAllFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        panelCTRLPanelLayout.setVerticalGroup(
            panelCTRLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCTRLPanelLayout.createSequentialGroup()
                .addGroup(panelCTRLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCTRLPanelLayout.createSequentialGroup()
                        .addGroup(panelCTRLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTrades)
                            .addComponent(btnAllocations)
                            .addComponent(btnPositions))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCTRLPanelLayout.createSequentialGroup()
                        .addGroup(panelCTRLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCTRLPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelHyphen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCTRLPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panelCTRLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDateRange, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCTRLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(textFieldStartDate)
                                    .addComponent(textFieldEndDate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(panelCTRLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxDateRange)
                            .addComponent(checkBoxSymbol))))
                .addGroup(panelCTRLPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCTRLPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelNumOfRecords))
                    .addComponent(btnClearAllFilters, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnPositions.getAccessibleContext().setAccessibleDescription("");

        scrollPaneSQL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textAreaSQL.setBackground(new java.awt.Color(153, 255, 204));
        textAreaSQL.setColumns(20);
        textAreaSQL.setRows(5);
        textAreaSQL.setText("Please input an SQL statement:\n>>");
        textAreaSQL.setText("Please input an SQL statement:\n>>");
        ((AbstractDocument) textAreaSQL.getDocument())
        .setDocumentFilter(new CreateDocumentFilter(33));
        scrollPaneSQL.setViewportView(textAreaSQL);

        btnEnterSQL.setText("Enter");
        btnEnterSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterSQLActionPerformed(evt);
            }
        });

        btnClearSQL.setText("Clear");
        btnClearSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSQLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSQLLayout = new javax.swing.GroupLayout(panelSQL);
        panelSQL.setLayout(panelSQLLayout);
        panelSQLLayout.setHorizontalGroup(
            panelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSQLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneSQL)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSQLLayout.createSequentialGroup()
                .addGap(455, 455, 455)
                .addComponent(btnEnterSQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClearSQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(426, 426, 426))
        );
        panelSQLLayout.setVerticalGroup(
            panelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSQLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneSQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnterSQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClearSQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout panelShowTablesLayout = new javax.swing.GroupLayout(panelShowTables);
        panelShowTables.setLayout(panelShowTablesLayout);
        panelShowTablesLayout.setHorizontalGroup(
            panelShowTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelShowTablesLayout.setVerticalGroup(
            panelShowTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        menuFile.setText("File");

        menuConnections.setText("Select Connections");

        menuItemLocal.setText("Local");
        menuItemLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLocalActionPerformed(evt);
            }
        });
        menuConnections.add(menuItemLocal);

        menuItemAWS.setText("AWS");
        menuItemAWS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAWSActionPerformed(evt);
            }
        });
        menuConnections.add(menuItemAWS);

        menuItemDummy.setText("Dummy");
        menuItemDummy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDummyActionPerformed(evt);
            }
        });
        menuConnections.add(menuItemDummy);

        menuFile.add(menuConnections);

        menuItemRead.setText("Read from Text File");
        menuItemRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReadActionPerformed(evt);
            }
        });
        menuFile.add(menuItemRead);

        menuPrint.setText("Print");

        menuItemPrintGUI.setText("Print GUI");
        menuItemPrintGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPrintGUIActionPerformed(evt);
            }
        });
        menuPrint.add(menuItemPrintGUI);

        menuItemPrintDisplayWindow.setText("Print Display Window");
        menuItemPrintDisplayWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPrintDisplayWindowActionPerformed(evt);
            }
        });
        menuPrint.add(menuItemPrintDisplayWindow);

        menuFile.add(menuPrint);

        menuItemSave.setText("Save File");
        menuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSaveActionPerformed(evt);
            }
        });
        menuFile.add(menuItemSave);

        jMenuBar1.add(menuFile);

        menuEdit.setText("Edit");

        menuItemConnection.setText("Connection...");
        menuItemConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConnectionActionPerformed(evt);
            }
        });
        menuEdit.add(menuItemConnection);

        jMenuBar1.add(menuEdit);

        menuFind.setText("Find");
        jMenuBar1.add(menuFind);

        menuReports.setText("Reports");
        jMenuBar1.add(menuReports);

        menuTools.setText("Tools");

        menuItemReconcile.setText("Reconcile 8949s");
        menuItemReconcile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReconcileActionPerformed(evt);
            }
        });
        menuTools.add(menuItemReconcile);

        menuItemShowMatches.setText("Show Matches");
        menuItemShowMatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemShowMatchesActionPerformed(evt);
            }
        });
        menuTools.add(menuItemShowMatches);

        menuItemIB8949.setText("IB 8949");
        menuItemIB8949.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIB8949ActionPerformed(evt);
            }
        });
        menuTools.add(menuItemIB8949);

        menuItemTL8949.setText("TL 8949");
        menuItemTL8949.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTL8949ActionPerformed(evt);
            }
        });
        menuTools.add(menuItemTL8949);

        jMenuBar1.add(menuTools);

        menuLoad.setText("Load");

        menuItemLoadFile.setText("Load File...");
        menuItemLoadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLoadFileActionPerformed(evt);
            }
        });
        menuLoad.add(menuItemLoadFile);

        jMenuBar1.add(menuLoad);

        menuView.setText("View");

        menuItemLog.setText("Log");
        menuItemLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLogActionPerformed(evt);
            }
        });
        menuView.add(menuItemLog);

        menuItemSqlCommand.setText("SQL Command");
        menuItemSqlCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSqlCommandActionPerformed(evt);
            }
        });
        menuView.add(menuItemSqlCommand);

        menuItemTrades.setText("Display Trades-All Fields");
        menuItemTrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTradesActionPerformed(evt);
            }
        });
        menuView.add(menuItemTrades);

        menuItemPositions.setText("Display Positions-All Fields");
        menuItemPositions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPositionsActionPerformed(evt);
            }
        });
        menuView.add(menuItemPositions);

        menuItemIB.setText("Display IB_8949-All Fields");
        menuItemIB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIBActionPerformed(evt);
            }
        });
        menuView.add(menuItemIB);

        menuItemTL.setText("Display TL_8949-All Fields");
        menuItemTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTLActionPerformed(evt);
            }
        });
        menuView.add(menuItemTL);

        menuItemLoadsTable.setText("Display Loads Table");
        menuItemLoadsTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLoadsTableActionPerformed(evt);
            }
        });
        menuView.add(menuItemLoadsTable);

        jMenuBar1.add(menuView);

        menuHelp.setText("Help");
        jMenuBar1.add(menuHelp);

        menuOther.setText("Other");
        jMenuBar1.add(menuOther);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelShowTables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCTRLPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCTRLPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelShowTables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelShowTables.getAccessibleContext().setAccessibleParent(panelShowTables);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPositionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPositionsActionPerformed

    }//GEN-LAST:event_btnPositionsActionPerformed

    private void btnTradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTradesActionPerformed

    }//GEN-LAST:event_btnTradesActionPerformed

    private void menuItemDummyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDummyActionPerformed

    }//GEN-LAST:event_menuItemDummyActionPerformed

    private void menuItemLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLocalActionPerformed

    }//GEN-LAST:event_menuItemLocalActionPerformed

    private void menuItemAWSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAWSActionPerformed

    }//GEN-LAST:event_menuItemAWSActionPerformed

    private void menuItemReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReadActionPerformed

    }//GEN-LAST:event_menuItemReadActionPerformed

    private void menuItemPrintGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPrintGUIActionPerformed

    }//GEN-LAST:event_menuItemPrintGUIActionPerformed

    private void menuItemPrintDisplayWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPrintDisplayWindowActionPerformed

    }//GEN-LAST:event_menuItemPrintDisplayWindowActionPerformed

    private void menuItemTradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTradesActionPerformed

    }//GEN-LAST:event_menuItemTradesActionPerformed

    private void menuItemLoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLoadFileActionPerformed

    }//GEN-LAST:event_menuItemLoadFileActionPerformed

    private void btnAllocationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllocationsActionPerformed

    }//GEN-LAST:event_btnAllocationsActionPerformed

    private void menuItemLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLogActionPerformed

    }//GEN-LAST:event_menuItemLogActionPerformed

    private void menuItemPositionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPositionsActionPerformed

    }//GEN-LAST:event_menuItemPositionsActionPerformed

    private void menuItemIBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIBActionPerformed

    }//GEN-LAST:event_menuItemIBActionPerformed

    private void menuItemTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTLActionPerformed

    }//GEN-LAST:event_menuItemTLActionPerformed

    private void menuItemLoadsTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLoadsTableActionPerformed

    }//GEN-LAST:event_menuItemLoadsTableActionPerformed

    private void menuItemSqlCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSqlCommandActionPerformed

    }//GEN-LAST:event_menuItemSqlCommandActionPerformed

    private void menuItemConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConnectionActionPerformed

    }//GEN-LAST:event_menuItemConnectionActionPerformed

    private void menuItemReconcileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReconcileActionPerformed

    }//GEN-LAST:event_menuItemReconcileActionPerformed

    private void btnSymbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSymbolActionPerformed

    }//GEN-LAST:event_btnSymbolActionPerformed

    private void btnDateRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateRangeActionPerformed

    }//GEN-LAST:event_btnDateRangeActionPerformed

    private void btnEnterSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterSQLActionPerformed

    }//GEN-LAST:event_btnEnterSQLActionPerformed

    private void btnClearSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSQLActionPerformed

    }//GEN-LAST:event_btnClearSQLActionPerformed

    private void menuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveActionPerformed

    }//GEN-LAST:event_menuItemSaveActionPerformed

    private void checkBoxDateRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxDateRangeActionPerformed

    }//GEN-LAST:event_checkBoxDateRangeActionPerformed

    private void checkBoxSymbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSymbolActionPerformed

    }//GEN-LAST:event_checkBoxSymbolActionPerformed

    private void btnClearAllFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAllFiltersActionPerformed

    }//GEN-LAST:event_btnClearAllFiltersActionPerformed

    private void menuItemShowMatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemShowMatchesActionPerformed

    }//GEN-LAST:event_menuItemShowMatchesActionPerformed

    private void menuItemIB8949ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIB8949ActionPerformed

    }//GEN-LAST:event_menuItemIB8949ActionPerformed

    private void menuItemTL8949ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTL8949ActionPerformed

    }//GEN-LAST:event_menuItemTL8949ActionPerformed


    @SuppressWarnings("unused")
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllocations;
    private java.awt.Button btnClearAllFilters;
    private javax.swing.JButton btnClearSQL;
    private javax.swing.JButton btnDateRange;
    private javax.swing.JButton btnEnterSQL;
    private javax.swing.JButton btnPositions;
    private javax.swing.JButton btnSymbol;
    private javax.swing.JButton btnTrades;
    private javax.swing.JCheckBox checkBoxDateRange;
    private javax.swing.JCheckBox checkBoxSymbol;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelHyphen;
    private javax.swing.JLabel labelNumOfRecords;
    private javax.swing.JMenu menuConnections;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuFind;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemAWS;
    private javax.swing.JMenuItem menuItemConnection;
    private javax.swing.JMenuItem menuItemDummy;
    private javax.swing.JMenuItem menuItemIB;
    private javax.swing.JMenuItem menuItemIB8949;
    private javax.swing.JMenuItem menuItemLoadFile;
    private javax.swing.JMenuItem menuItemLoadsTable;
    private javax.swing.JMenuItem menuItemLocal;
    private javax.swing.JMenuItem menuItemLog;
    private javax.swing.JMenuItem menuItemPositions;
    private javax.swing.JMenuItem menuItemPrintDisplayWindow;
    private javax.swing.JMenuItem menuItemPrintGUI;
    private javax.swing.JMenuItem menuItemRead;
    private javax.swing.JMenuItem menuItemReconcile;
    private javax.swing.JMenuItem menuItemSave;
    private javax.swing.JMenuItem menuItemShowMatches;
    private javax.swing.JMenuItem menuItemSqlCommand;
    private javax.swing.JMenuItem menuItemTL;
    private javax.swing.JMenuItem menuItemTL8949;
    private javax.swing.JMenuItem menuItemTrades;
    private javax.swing.JMenu menuLoad;
    private javax.swing.JMenu menuOther;
    private javax.swing.JMenu menuPrint;
    private javax.swing.JMenu menuReports;
    private javax.swing.JMenu menuTools;
    private javax.swing.JMenu menuView;
    private javax.swing.JPanel panelCTRLPanel;
    private javax.swing.JPanel panelSQL;
    private javax.swing.JPanel panelShowTables;
    private javax.swing.JScrollPane scrollPaneSQL;
    private javax.swing.JTextArea textAreaSQL;
    private javax.swing.JTextField textFieldEndDate;
    private javax.swing.JTextField textFieldStartDate;
    private javax.swing.JTextField textFieldSymbol;
    // End of variables declaration//GEN-END:variables

}
