
package com.elle.elle_gui.presentation;

import com.elle.elle_gui.old.CreateDocumentFilter;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author Louis W.
 */
public class ELLE_GUI_Frame extends javax.swing.JFrame {

    /**
     * Creates new form GUI2
     */
    public ELLE_GUI_Frame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Elle GUI");
        setDefaultCloseOperation(this.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBPositions = new javax.swing.JButton();
        jBTrades = new javax.swing.JButton();
        jBAllocations = new javax.swing.JButton();
        jBSymbol = new javax.swing.JButton();
        jBDateRange = new javax.swing.JButton();
        numOfRecords = new javax.swing.JLabel();
        jLConnect = new javax.swing.JLabel();
        jCSymbol = new javax.swing.JCheckBox();
        jCDateRange = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTSymbol = new javax.swing.JTextField();
        jTStartDate = new javax.swing.JTextField();
        jTEndDate = new javax.swing.JTextField();
        clearAllFilters = new java.awt.Button();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jText = new javax.swing.JTextArea();
        jEnter = new javax.swing.JButton();
        jClear = new javax.swing.JButton();
        jPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMFile = new javax.swing.JMenu();
        jMFileConnections = new javax.swing.JMenu();
        jMFileConnLocal = new javax.swing.JMenuItem();
        jMFileConnAWS = new javax.swing.JMenuItem();
        jMFileConnDummy = new javax.swing.JMenuItem();
        jMFileRead = new javax.swing.JMenuItem();
        jMFilePrint = new javax.swing.JMenu();
        jMFilePrintGUI = new javax.swing.JMenuItem();
        jMFilePrintWindow = new javax.swing.JMenuItem();
        jMFileSave = new javax.swing.JMenuItem();
        jMEdit = new javax.swing.JMenu();
        jMEditConnection = new javax.swing.JMenuItem();
        jMFind = new javax.swing.JMenu();
        jMReports = new javax.swing.JMenu();
        jMTools = new javax.swing.JMenu();
        jMToolsReconcile = new javax.swing.JMenuItem();
        menuItemShowMatches = new javax.swing.JMenuItem();
        menuItemIB8949 = new javax.swing.JMenuItem();
        menuItemTL8949 = new javax.swing.JMenuItem();
        jMLoad = new javax.swing.JMenu();
        jMLoadFile = new javax.swing.JMenuItem();
        jMView = new javax.swing.JMenu();
        jMViewLog = new javax.swing.JMenuItem();
        jMViewSql = new javax.swing.JMenuItem();
        jMViewTrades = new javax.swing.JMenuItem();
        jMViewPositions = new javax.swing.JMenuItem();
        jMViewIB = new javax.swing.JMenuItem();
        jMViewTL = new javax.swing.JMenuItem();
        jMViewLoadsTable = new javax.swing.JMenuItem();
        jMHelp = new javax.swing.JMenu();
        jMOther = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBPositions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elle/elle_gui/images/button1.png"))); // NOI18N
        jBPositions.setText("Positions");
        jBPositions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBPositions.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBPositions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPositionsActionPerformed(evt);
            }
        });

        jBTrades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elle/elle_gui/images/button1.png"))); // NOI18N
        jBTrades.setText("Trades");
        jBTrades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBTrades.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBTrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTradesActionPerformed(evt);
            }
        });

        jBAllocations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elle/elle_gui/images/button3.png"))); // NOI18N
        jBAllocations.setText("Allocations");
        jBAllocations.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBAllocations.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBAllocations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAllocationsActionPerformed(evt);
            }
        });

        jBSymbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elle/elle_gui/images/filter.png"))); // NOI18N
        jBSymbol.setText(" ");
        jBSymbol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSymbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSymbolActionPerformed(evt);
            }
        });

        jBDateRange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elle/elle_gui/images/filter.png"))); // NOI18N
        jBDateRange.setText(" ");
        jBDateRange.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBDateRange.setIconTextGap(0);
        jBDateRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDateRangeActionPerformed(evt);
            }
        });

        numOfRecords.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        numOfRecords.setText("Number of Records: 0");

        jCSymbol.setText("Symbol");
        jCSymbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCSymbolActionPerformed(evt);
            }
        });

        jCDateRange.setText("Date Range");
        jCDateRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCDateRangeActionPerformed(evt);
            }
        });

        jLabel1.setText("-");

        clearAllFilters.setActionCommand("Clear All Filters");
        clearAllFilters.setLabel("Clear All Filters");
        clearAllFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllFiltersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBPositions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTrades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(numOfRecords)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAllocations)
                .addGap(334, 334, 334)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCDateRange)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBDateRange, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(clearAllFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBTrades)
                            .addComponent(jBAllocations)
                            .addComponent(jBPositions))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBDateRange, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jBSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTStartDate)
                                    .addComponent(jTEndDate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCDateRange)
                            .addComponent(jCSymbol))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(numOfRecords))
                    .addComponent(jLConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearAllFilters, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jBPositions.getAccessibleContext().setAccessibleDescription("");

        jScrollPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText.setBackground(new java.awt.Color(153, 255, 204));
        jText.setColumns(20);
        jText.setRows(5);
        jText.setText("Please input an SQL statement:\n>>");
        jText.setText("Please input an SQL statement:\n>>");
        ((AbstractDocument) jText.getDocument())
        .setDocumentFilter(new CreateDocumentFilter(33));
        jScrollPane4.setViewportView(jText);

        jEnter.setText("Enter");
        jEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEnterActionPerformed(evt);
            }
        });

        jClear.setText("Clear");
        jClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(455, 455, 455)
                .addComponent(jEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(426, 426, 426))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        jMFile.setText("File");

        jMFileConnections.setText("Select Connections");

        jMFileConnLocal.setText("Local");
        jMFileConnLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFileConnLocalActionPerformed(evt);
            }
        });
        jMFileConnections.add(jMFileConnLocal);

        jMFileConnAWS.setText("AWS");
        jMFileConnAWS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFileConnAWSActionPerformed(evt);
            }
        });
        jMFileConnections.add(jMFileConnAWS);

        jMFileConnDummy.setText("Dummy");
        jMFileConnDummy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFileConnDummyActionPerformed(evt);
            }
        });
        jMFileConnections.add(jMFileConnDummy);

        jMFile.add(jMFileConnections);

        jMFileRead.setText("Read from Text File");
        jMFileRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFileReadActionPerformed(evt);
            }
        });
        jMFile.add(jMFileRead);

        jMFilePrint.setText("Print");

        jMFilePrintGUI.setText("Print GUI");
        jMFilePrintGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFilePrintGUIActionPerformed(evt);
            }
        });
        jMFilePrint.add(jMFilePrintGUI);

        jMFilePrintWindow.setText("Print Display Window");
        jMFilePrintWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFilePrintWindowActionPerformed(evt);
            }
        });
        jMFilePrint.add(jMFilePrintWindow);

        jMFile.add(jMFilePrint);

        jMFileSave.setText("Save File");
        jMFileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFileSaveActionPerformed(evt);
            }
        });
        jMFile.add(jMFileSave);

        jMenuBar1.add(jMFile);

        jMEdit.setText("Edit");

        jMEditConnection.setText("Connection...");
        jMEditConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMEditConnectionActionPerformed(evt);
            }
        });
        jMEdit.add(jMEditConnection);

        jMenuBar1.add(jMEdit);

        jMFind.setText("Find");
        jMenuBar1.add(jMFind);

        jMReports.setText("Reports");
        jMenuBar1.add(jMReports);

        jMTools.setText("Tools");

        jMToolsReconcile.setText("Reconcile 8949s");
        jMToolsReconcile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMToolsReconcileActionPerformed(evt);
            }
        });
        jMTools.add(jMToolsReconcile);

        menuItemShowMatches.setText("Show Matches");
        menuItemShowMatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemShowMatchesActionPerformed(evt);
            }
        });
        jMTools.add(menuItemShowMatches);

        menuItemIB8949.setText("IB 8949");
        menuItemIB8949.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIB8949ActionPerformed(evt);
            }
        });
        jMTools.add(menuItemIB8949);

        menuItemTL8949.setText("TL 8949");
        menuItemTL8949.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTL8949ActionPerformed(evt);
            }
        });
        jMTools.add(menuItemTL8949);

        jMenuBar1.add(jMTools);

        jMLoad.setText("Load");

        jMLoadFile.setText("Load File...");
        jMLoadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMLoadFileActionPerformed(evt);
            }
        });
        jMLoad.add(jMLoadFile);

        jMenuBar1.add(jMLoad);

        jMView.setText("View");

        jMViewLog.setText("Log");
        jMViewLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMViewLogActionPerformed(evt);
            }
        });
        jMView.add(jMViewLog);

        jMViewSql.setText("SQL Command");
        jMViewSql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMViewSqlActionPerformed(evt);
            }
        });
        jMView.add(jMViewSql);

        jMViewTrades.setText("Display Trades-All Fields");
        jMViewTrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMViewTradesActionPerformed(evt);
            }
        });
        jMView.add(jMViewTrades);

        jMViewPositions.setText("Display Positions-All Fields");
        jMViewPositions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMViewPositionsActionPerformed(evt);
            }
        });
        jMView.add(jMViewPositions);

        jMViewIB.setText("Display IB_8949-All Fields");
        jMViewIB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMViewIBActionPerformed(evt);
            }
        });
        jMView.add(jMViewIB);

        jMViewTL.setText("Display TL_8949-All Fields");
        jMViewTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMViewTLActionPerformed(evt);
            }
        });
        jMView.add(jMViewTL);

        jMViewLoadsTable.setText("Display Loads Table");
        jMViewLoadsTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMViewLoadsTableActionPerformed(evt);
            }
        });
        jMView.add(jMViewLoadsTable);

        jMenuBar1.add(jMView);

        jMHelp.setText("Help");
        jMenuBar1.add(jMHelp);

        jMOther.setText("Other");
        jMenuBar1.add(jMOther);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel.getAccessibleContext().setAccessibleParent(jPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPositionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPositionsActionPerformed

    }//GEN-LAST:event_jBPositionsActionPerformed

    private void jBTradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTradesActionPerformed

    }//GEN-LAST:event_jBTradesActionPerformed

    private void jMFileConnDummyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFileConnDummyActionPerformed

    }//GEN-LAST:event_jMFileConnDummyActionPerformed

    private void jMFileConnLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFileConnLocalActionPerformed

    }//GEN-LAST:event_jMFileConnLocalActionPerformed

    private void jMFileConnAWSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFileConnAWSActionPerformed

    }//GEN-LAST:event_jMFileConnAWSActionPerformed

    private void jMFileReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFileReadActionPerformed

    }//GEN-LAST:event_jMFileReadActionPerformed

    private void jMFilePrintGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFilePrintGUIActionPerformed

    }//GEN-LAST:event_jMFilePrintGUIActionPerformed

    private void jMFilePrintWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFilePrintWindowActionPerformed

    }//GEN-LAST:event_jMFilePrintWindowActionPerformed

    private void jMViewTradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMViewTradesActionPerformed

    }//GEN-LAST:event_jMViewTradesActionPerformed

    private void jMLoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMLoadFileActionPerformed

    }//GEN-LAST:event_jMLoadFileActionPerformed

    private void jBAllocationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAllocationsActionPerformed

    }//GEN-LAST:event_jBAllocationsActionPerformed

    private void jMViewLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMViewLogActionPerformed

    }//GEN-LAST:event_jMViewLogActionPerformed

    private void jMViewPositionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMViewPositionsActionPerformed

    }//GEN-LAST:event_jMViewPositionsActionPerformed

    private void jMViewIBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMViewIBActionPerformed

    }//GEN-LAST:event_jMViewIBActionPerformed

    private void jMViewTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMViewTLActionPerformed

    }//GEN-LAST:event_jMViewTLActionPerformed

    private void jMViewLoadsTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMViewLoadsTableActionPerformed

    }//GEN-LAST:event_jMViewLoadsTableActionPerformed

    private void jMViewSqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMViewSqlActionPerformed

    }//GEN-LAST:event_jMViewSqlActionPerformed

    private void jMEditConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMEditConnectionActionPerformed

    }//GEN-LAST:event_jMEditConnectionActionPerformed

    private void jMToolsReconcileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMToolsReconcileActionPerformed

    }//GEN-LAST:event_jMToolsReconcileActionPerformed

    private void jBSymbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSymbolActionPerformed

    }//GEN-LAST:event_jBSymbolActionPerformed

    private void jBDateRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDateRangeActionPerformed

    }//GEN-LAST:event_jBDateRangeActionPerformed

    private void jEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEnterActionPerformed

    }//GEN-LAST:event_jEnterActionPerformed

    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed

    }//GEN-LAST:event_jClearActionPerformed

    private void jMFileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFileSaveActionPerformed

    }//GEN-LAST:event_jMFileSaveActionPerformed

    private void jCDateRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCDateRangeActionPerformed

    }//GEN-LAST:event_jCDateRangeActionPerformed

    private void jCSymbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCSymbolActionPerformed

    }//GEN-LAST:event_jCSymbolActionPerformed

    private void clearAllFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllFiltersActionPerformed

    }//GEN-LAST:event_clearAllFiltersActionPerformed

    private void menuItemShowMatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemShowMatchesActionPerformed

    }//GEN-LAST:event_menuItemShowMatchesActionPerformed

    private void menuItemIB8949ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIB8949ActionPerformed

    }//GEN-LAST:event_menuItemIB8949ActionPerformed

    private void menuItemTL8949ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTL8949ActionPerformed

    }//GEN-LAST:event_menuItemTL8949ActionPerformed


    @SuppressWarnings("unused")
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button clearAllFilters;
    private javax.swing.JButton jBAllocations;
    private javax.swing.JButton jBDateRange;
    private javax.swing.JButton jBPositions;
    private javax.swing.JButton jBSymbol;
    private javax.swing.JButton jBTrades;
    private javax.swing.JCheckBox jCDateRange;
    private javax.swing.JCheckBox jCSymbol;
    private javax.swing.JButton jClear;
    private javax.swing.JButton jEnter;
    private javax.swing.JLabel jLConnect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMEdit;
    private javax.swing.JMenuItem jMEditConnection;
    private javax.swing.JMenu jMFile;
    private javax.swing.JMenuItem jMFileConnAWS;
    private javax.swing.JMenuItem jMFileConnDummy;
    private javax.swing.JMenuItem jMFileConnLocal;
    private javax.swing.JMenu jMFileConnections;
    private javax.swing.JMenu jMFilePrint;
    private javax.swing.JMenuItem jMFilePrintGUI;
    private javax.swing.JMenuItem jMFilePrintWindow;
    private javax.swing.JMenuItem jMFileRead;
    private javax.swing.JMenuItem jMFileSave;
    private javax.swing.JMenu jMFind;
    private javax.swing.JMenu jMHelp;
    private javax.swing.JMenu jMLoad;
    private javax.swing.JMenuItem jMLoadFile;
    private javax.swing.JMenu jMOther;
    private javax.swing.JMenu jMReports;
    private javax.swing.JMenu jMTools;
    private javax.swing.JMenuItem jMToolsReconcile;
    private javax.swing.JMenu jMView;
    private javax.swing.JMenuItem jMViewIB;
    private javax.swing.JMenuItem jMViewLoadsTable;
    private javax.swing.JMenuItem jMViewLog;
    private javax.swing.JMenuItem jMViewPositions;
    private javax.swing.JMenuItem jMViewSql;
    private javax.swing.JMenuItem jMViewTL;
    private javax.swing.JMenuItem jMViewTrades;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTEndDate;
    private javax.swing.JTextField jTStartDate;
    private javax.swing.JTextField jTSymbol;
    private javax.swing.JTextArea jText;
    private javax.swing.JMenuItem menuItemIB8949;
    private javax.swing.JMenuItem menuItemShowMatches;
    private javax.swing.JMenuItem menuItemTL8949;
    private javax.swing.JLabel numOfRecords;
    // End of variables declaration//GEN-END:variables

}
